---
# - include: create_user_credentials.yml
#   vars:
#     username: glance
#     password: "{{ openstack_glance_keystone_password }}"
#     project: service
#     role: admin
#     project_description: "project description"
#   environment: "{{ token_auth_env }}"

- name: 'Check "{{ username }}" role exists'
  command: openstack user show "{{ username }}"
  register: userExist
  ignore_errors: True
  run_once: True

- name: 'Create the "{{ username }}" user'
  command: |
    openstack user create  --domain default \
    --password "{{ password }}" \
    "{{ username }}"
  when: userExist|failed
  run_once: True

- name: 'Check "{{ role }}" role exists'
  command: openstack role show "{{ role }}"
  register: roleExist
  ignore_errors: True
  run_once: True

- name: 'Create the "{{ role }}" role'
  command: openstack role create "{{ role }}"
  when: roleExist|failed
  run_once: True

- name: 'Check the "{{ project }}" project exists'
  command: openstack project show "{{ project }}"
  register: projectExist
  ignore_errors: True
  run_once: True

- name: 'Create the "{{ project }}" project'
  command: |
    openstack project create  --domain default \
    --description "{{ project_description }}" "{{ project }}"
  when: projectExist|failed
  run_once: True

- name: 'Add "{{ role }}" role to the "{{ username }}" user and "{{ project }}" project'
  command: |
    openstack role add --project "{{ project }}" \
    --user "{{ username }}" "{{ role }}"
  run_once: True