---
# tasks file for keystone

# Prerequisites
- name: Prepare Database for keystone.
  include: database.yml
  vars:
    db_name: "{{ openstack_keystone_db_name }}"
    db_user: "{{ openstack_keystone_db_user }}"
    db_password: "{{ openstack_keystone_db_password }}"
    db_priv: "{{ openstack_keystone_db_name }}.*:ALL"
  tags: database

- name: Install OpenStack keystone package.
  yum: name={{ item }} state=latest
  with_items:
    - openstack-keystone
  retries: 2
  delay: 5

#rabbit
- name: Service rabbitmq
  service: name=rabbitmq-server enabled=yes state=restarted

- name: rabbitmq user setup
  rabbitmq_user: user={{ rabbit_user }}
                 password={{ rabbit_pass }}
                 vhost=/
                 configure_priv=.*
                 read_priv=.*
                 write_priv=.*
                 state=present

- name: Deploy keyston configuration files from templates
  template: src={{ item.src }} dest={{ item.dest }} mode=0640 owner=keystone group=apache backup=yes
  with_items:
    - { src: 'keystone/keystone-dist-paste.ini.j2', dest: '/etc/keystone/keystone-dist-paste.ini' }
    - { src: 'keystone/keystone.conf.j2', dest: '/etc/keystone/keystone.conf' }
    - { src: 'keystone/policy.json.j2', dest: '/etc/keystone/policy.json' }
    - { src: 'keystone/wsgi-keystone.conf.j2', dest: '/etc/httpd/conf.d/wsgi-keystone.conf' }

- name: Service http
  service: name=httpd enabled=yes state=restarted

- name: Waiting for keystone service is started.
  wait_for: "host={{ openstack_controller_host }} port=35357 delay=10 timeout=30"
  run_once: true

- name: Give permissions to keystone.log
  file: path=/var/log/keystone/keystone.log state=touch mode=0640 owner=keystone group=apache

- name:  Create keystone tables in DB
  shell: keystone-manage db_sync
  become_user: keystone
  run_once: True

- name: Initialize fernet tokens
  command: keystone-manage fernet_setup --keystone-user keystone --keystone-group keystone

- name: Service http
  service: name=httpd enabled=yes state=restarted

- name: Create the service entity for keystone.
  include: service_create.yml
  vars:
    name: keystone
    type: identity
    description: OpenStack Identity

- name: Create the API endpoint for keystone.
  include: endpoint_create.yml
  vars:
    service: identity
    region: RegionOne
    endpoints:
      adminurl: "{{ openstack_endpoint_admin_url }}"
      internalurl: "{{ openstack_endpoint_internal_url }}"
      publicurl: "{{ openstack_endpoint_public_url }}"

# admin
- name: "Admin credentials: create user, project and role. Link them"
  include: create_user_credentials.yml
  vars:
    username: admin
    password: "{{ openstack_admin_password }}"
    project: admin
    project_description: "Admin project"
    role: admin
  environment: "{{ token_auth_env }}"

# user
- name: "User credentials: create user, project and role. Link them"
  include: create_user_credentials.yml
  vars:
    username: "{{ openstack_user_name }}"
    password: "{{ openstack_user_password }}"
    project: "{{ openstack_user_project }}"
    project_description: "Demo project"
    role: "{{ openstack_user_role }}"
  environment: "{{ token_auth_env }}"

#service
- name: "Create the service project"
  command: |
    openstack project create  --domain default \
    --description "Service project" service
  environment: "{{ token_auth_env }}"
  run_once: True
