---
# Pre deployment tasks

- name: Install required packages
  yum: name="{{ item }}" state=latest
  with_items:
    - curl
    - git
    - python-devel
    - python-pip
    - tar
    - wget

- name: Install yum-plugin-priorities and epel-release
  yum: name="{{ item }}" state=latest
  with_items:
    - yum-plugin-priorities
    - epel-release

- name: Install Openstack {{ openstack_version | default(liberty) }}  packages
  yum: name="{{ item }}" state=latest
  with_items:
    - centos-release-openstack-{{ openstack_version | default(liberty) }}

- name: Upudate cache and install the openstack-selinux package
  yum: name="{{ item }}" state=latest
   # update_cache=yes
  with_items:
    - openstack-selinux

# openstack shade will be used later on in the deploy/config of OS
- name: pip update and install openstack shade
  pip: name={{ item }} state=latest
  with_items:
    - pip
    - shade
