---
# Pre deployment tasks

- name: Install mariadb and several other packages
  yum: name="{{ item }}" state=latest
  with_items:
    - curl
    - git
    - mariadb-server
    - mariadb
    - python-devel
    - python-pip
    - tar
    - wget

# openstack shade will be used later on in the deploy/config of OS
- name: pip update and install openstack shade
  pip: name={{ item }} state=latest
  with_items:
    - pip
    - shade


- name: Ensure service is started and that it always starts on boot
  service: name=mariadb state=started enabled=yes

- name: 'Setup DB root user'
  mysql_user:
    name: "root"
    password: "{{ db_root_password }}"
    host: "{{ item }}"
    priv: "{{ db_priv | default('*.*:ALL') }}"
    login_host: "{{ openstack_database_host }}"
    login_user: "{{ openstack_database_root | default('root') }}"
    login_password: "{{ openstack_database_root_password }}"
    state: present
  with_items:
    - localhost
    - "%"
  run_once: True
