---
# Pre deployment tasks

- name: Install yum-plugin-priorities and epel-release
  yum: name="{{ item }}" state=latest
  with_items:
    - epel-release
    - yum-plugin-priorities

- name: Install required packages
  yum: name="{{ item }}" state=latest update_cache=yes
  with_items:
    - curl
    - git
    - python-devel
    - python-pip
    - tar
    - bind-utils
    - wget
    - httpd
    - memcached
    - mod_wsgi
    - rabbitmq-server
    - iptables
    - iptables-services

- name: Install Openstack "{{ openstack_version | default(liberty) }}"  packages
  yum: name="{{ item }}" state=latest update_cache=yes
  with_items:
    - centos-release-openstack-{{ openstack_version | default(liberty) }}

- name: Install python-openstackclient
  yum: name="{{ item }}" state=latest
  with_items:
    - python-openstackclient

# todo(jorgesece): move to new role
- name: Set hostame to "{{ openstack_controller_host }}"
  when: not "{{ local_compute_node }}"
  shell: hostnamectl set-hostname "{{ openstack_controller_host }}"


- name: Add "{{ openstack_controller_host }}" to hosts file
  shell: echo "{{ openstack_controller_ip }} {{ openstack_controller_host }}" >> /etc/hosts


- name: Set hostame to "{{ openstack_controller_host }}"
  shell: hostnamectl set-hostname "{{ openstack_controller_host }}"
  ignore_errors: True