---
# tasks file for horizon
# Prerequisites

- name: Create the service user for swift.
  include: openstack/create_user_in_project.yml
  vars:
    username: swift
    password: "{{ openstack_swift_keystone_password }}"
    project: service
    role: admin

- name: Create the service entity for neutron.
  include: openstack/create_service.yml
  vars:
    name: swift
    type: object-store
    description: OpenStack Networking

- name: Create the API endpoint for swift.
  include: openstack/create_endpoint.yml
  vars:
    service: object-store
    region: RegionOne
    endpoints:
      adminurl: "{{ openstack_swift_adminurl }}"
      internalurl: "{{ openstack_swift_internalurl }}"
      publicurl: "{{ openstack_swift_publicurl }}"

# Install and configure
- name: Install OpenStack swift packages.
  yum: name={{ item }} state=installed
  with_items:
    - openstack-swift-proxy
    - python-swiftclient
    - python-keystoneclient
    - python-keystonemiddleware
    - memcached

- name: Ensures "/etc/swift" dir exists
  file: path=/etc/swift state=directory
  become_user: swift

- name: Deploy swift configuration files from templates
  template: src={{ item.src }} dest={{ item.dest }} backup=yes
  with_items:
    - { src: 'swift/proxy-server.conf.j2', dest: '/etc/swift/proxy-server.conf' }

- name: Ensure images service is started and enabled on boot
  service: name={{ item }} enabled=yes state=started
  with_items:
    - openstack-swift-proxy
    - memcached